services:
  geo-deep-learning:
    build:
      dockerfile: Dockerfile
#    env_file:
#      - .env
    user: '9005:ubuntu'
    container_name: geo-deep-learning
    volumes:
      - "/mnt/projet_RCM_scanfire:/mnt/projet_RCM_scanfire:rw"
