# lightning.pytorch==2.3.2
seed_everything: true

trainer:
  accelerator: "gpu"
  devices: -1
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
    init_args:
      find_unused_parameters: false
      gradient_as_bucket_view: true
      static_graph: true
  sync_batchnorm: true
  logger:
    class_path: lightning.pytorch.loggers.mlflow.MLFlowLogger
    init_args:
      save_dir: /space/partner/nrcan/geobase/work/transfer/work/deep_learning/mlflow/mlruns/
      log_model: all
      experiment_name: "gdl_experiment"
      run_name: "gdl_run"
  callbacks:
    class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: "val_loss"
      mode: "min"
      patience: 1
    class_path: tools.callbacks.segmentation_callback.SegmentationCallback
    init_args:
      max_samples: 3
      class_colors: ["#000000", "#008000", "#0000FF", "#FFFF00", "#FF0000"] # black, green, blue, yellow, red
      monitor: "val_loss"
      mode: "min"
      save_top_k: 1
      filename: "model-{epoch:02d}-{val_loss:.2f}"
  max_epochs: 20
  min_epochs: 2

model:
  class_path: tasks_with_models.segmentation_dofa.SegmentationDOFA
  init_args:
    encoder: "dofa_base" # "dofa_base" or "dofa_large"
    pretrained: True
    image_size: [512, 512]
    in_channels: 3
    num_classes: 5
    loss: 
      class_path: segmentation_models_pytorch.losses.DiceLoss
      init_args:
        mode: "multiclass"
    class_labels: ["background", "fore", "hydro", "roads", "buildings"]

optimizer:
  class_path: Adam
  init_args:
    lr: 0.001

lr_scheduler: 
  class_path: ReduceLROnPlateau
  init_args:
    monitor: "val_loss"
    mode: "min"
    factor: 0.1
    patience: 2

data:
  class_path: datamodules.imagery_NonGeoDataModule.BlueSkyNonGeoDataModule
  init_args:
    batch_size: 32
    num_workers: 4
    data_type_max: 255
    patch_size:
    - 512
    - 512
    mean:
    - 0.399
    - 0.428
    - 0.399
    std:
    - 0.167
    - 0.180
    - 0.158
    csv_root_folder: /gpfs/fs5/nrcan/nrcan_geobase/work/transfer/work/deep_learning/models/multi/RGB/quarte_classes/DG_PS_SP_NB_QC_NFL/maxar_rgb/wv_geoeye_quickbird
    patches_root_folder: /gpfs/fs5/nrcan/nrcan_geobase/work/transfer/work/deep_learning/models/multi/RGB/quarte_classes/DG_PS_SP_NB_QC_NFL/maxar_rgb/wv_geoeye_quickbird

ckpt_path: null