# @package _global_
dataset:
  # dataset-wide
  name: pre_post_datasets
  raw_data_csv: ${general.raw_data_dir}/pre_post_datasets.csv
  raw_data_dir: ${general.raw_data_dir}/raw
  download_data: False
  train_test_val_split: [0.7, 0.15, 0.15]  # train, test, val
  split_seed: 42 # for reproducibility (and 42 is the answer to everything)

  # imagery
  bands: ['M','LOCALINCANGLE','RL','RR','S0', 'SP1','SP2','SP3','RFDI']
  # RCM bands AVAILABLE

  #    BITMASK_CROPPED
  #    LOCALINCANGLE
  #    M
  #    NDSV
  #    PDN
  #    PSN
  #    PVN
  #    RFDI
  #    RL
  #    RR
  #    S0
  #    SP1
  #    SP2
  #    SP3

  beam_filter: # 'A'  # AVAILABLE: ['A','B','C','D']
  satellite_pass_filter: # 'Descending'  # AVAILABLE: ['Ascending','Descending']

  # TODO : Ajouter éventuellement un filtrage sur un timelag

  # ground truth
  # No Data in RCM dataset: NO_DATA = 32767
  ignore_index: 32767
  attribute_field: properties/class
  attribute_values: [1]
  class_name: # will follow in the next version
  classes_dict: {'BURN':1}
  class_weights:
